{
  "name": "Export version",
  "inputs": {
    "token": {
      "description": "GitHub Token",
      "required": true
    }
  },
  "description": "Export version based on the ref",
  "outputs": {
    "full-tag": {
      "description": "The full tag"
    }
  },
  "runs": {
    "using": "node20",
    "main": "dist/actions-setup-version-main.mjs"
  }
}
