{
  "name": "Export version",
  "inputs": {
    "token": {
      "description": "GitHub Token",
      "required": false
    }
  },
  "description": "Export version based on the ref",
  "outputs": {
    "ref": {
      "description": "The ref"
    },
    "version": {
      "description": "The version"
    }
  },
  "runs": {
    "using": "node20",
    "main": "dist/actions-setup-version-main.mjs"
  }
}
